# dotnetproject pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Trigger on commits to the main branch

pool: myUbuntuAgentPool  # Use a configured Ubuntu agent pool

steps:
- script: |
    echo "Logging in to Docker registry..."
    echo "$(REGISTRY_PASS)" | docker login -u "$(REGISTRY_USER)" --password-stdin || { echo "Docker login failed"; exit 1; }
  displayName: 'Docker Login'

- script: |
    echo "Pulling Docker image..."
    docker pull $(REGISTRY_USER)/dotnetproject:latest || { echo "Pull failed"; exit 1; }
  displayName: 'Pull Docker Image'

- script: |
    echo "Deploying application..."
    docker run -d -p 3001:80 $(REGISTRY_USER)/dotnetproject:latest || { echo "Run failed"; exit 1; }
  displayName: 'Deploy Application'
